SPIN_APP_NAME = copy_to_host
SPIN_APP_SRCS = copy_to_host.c
SPIN_CFLAGS = -O3 -g -flto
SPIN_LDFLAGS = -lm
NUM_PACKETS ?= 512
PKT_DELAY ?= 0
MSG_DELAY ?= 0
HAS_HH ?= 0
HAS_TH ?= 0
FULL_PKT ?= 1

include $(PSPIN_RT)/spin-handlers.mk

