SPIN_APP_NAME = aggregate_and_reduce
SPIN_APP_SRCS = handlers/aggregate_and_reduce.c
SPIN_CFLAGS = -O3 -g
SPIN_LDFLAGS = -lm

include $(PSPIN_RT)/rules/spin-handlers.mk
include ../generic_driver/gdriver.mk
