SPIN_APP_NAME = aggregate_global
SPIN_APP_SRCS = aggregate_global.c
SPIN_CFLAGS = -O3 -g
SPIN_LDFLAGS = -lm 
NUM_PACKETS ?=512
HAS_HH=0
HAS_TH=1
FULL_PKT=1
PKT_SIZE ?= 1024
PKT_DELAY=0

include $(PSPIN_RT)/spin-handlers.mk

